### ISSUE TITLE
ConfigurationSection.ToString returns type name, not contents

### ISSUE THREAD

**Issue by rktect** [toddabel/PQService#1]
(5.4.145/2.4.145) When testing a configuration update for a change based on a hash of the configuration name/value pairs, [this line](https://github.com/toddabel/PQService/blob/master/src/QuickService.Common/Configuration/ConfigurationProvider.cs#L231) will never detect a change, since ConfigurationSection.ToString just returns the type name - not a representation of the name/value pairs.

I didn't see an extension method to accommodate this. I got around this with a quick string solution:

    string sectionContent = string.Join("|", section.Parameters.Select(p => $"{p.Name}~{p.Value}"));
    byte[] hash = md5.ComputeHash(Encoding.UTF8.GetBytes(sectionContent));

**Comment by toddabel** [comment]
You want to create a PR will the fix?

**Comment by rktect** [comment]
Sure thing - will do.
